name: cursor_trail
description: A widget that shows a trail of widgets/images as you move your cursor.

version: 0.1.1

homepage: https://github.com/birjuvachhani/cursor_trail

screenshots:
  - description: Logo for the package
    path: resources/logo.png
  - description: Demo showing example app of the package.
    path: resources/demo.gif

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

scripts: scripts.yaml