name: cursor_trail
description: A pictures stack that follow your cursor.

version: 0.1.0

homepage: https://github.com/birjuvachhani/cursor_trail

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

scripts: scripts.yaml